services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:17.5-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:


# connect with psql
# psql -p 5432 -U postgres -d postgres_db -W -h localhost